# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc2515f5cd76ed7731c16663e0dd25fd32f662d15d3cc3f2553a350b65c23d27a185dda21e6f02ba933727e851ceb4d2bbaa00c86927a63f12e5a7bea32be6fe

test:
  secret_key_base: 1a845932aeb0a020590928535e8f6653e31c3e536fa042720d89a08e5a3e7ccb019e7d61a8e078209a5f9347cec5dc3bc6673cfe7a82fcb7b1d5e59d49bebb4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 180671409091690
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
